//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaCabinInc
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TeamSchedule", Namespace="http://schemas.datacontract.org/2004/07/PizzaCabinInc")]
    public partial class TeamSchedule : object
    {
        
        private PizzaCabinInc.Schedule[] SchedulesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PizzaCabinInc.Schedule[] Schedules
        {
            get
            {
                return this.SchedulesField;
            }
            set
            {
                this.SchedulesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Schedule", Namespace="http://schemas.datacontract.org/2004/07/PizzaCabinInc")]
    public partial class Schedule : object
    {
        
        private int ContractTimeMinutesField;
        
        private System.DateTime DateField;
        
        private bool IsFullDayAbsenceField;
        
        private string NameField;
        
        private System.Guid PersonIdField;
        
        private PizzaCabinInc.Activity[] ProjectionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContractTimeMinutes
        {
            get
            {
                return this.ContractTimeMinutesField;
            }
            set
            {
                this.ContractTimeMinutesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFullDayAbsence
        {
            get
            {
                return this.IsFullDayAbsenceField;
            }
            set
            {
                this.IsFullDayAbsenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonId
        {
            get
            {
                return this.PersonIdField;
            }
            set
            {
                this.PersonIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PizzaCabinInc.Activity[] Projection
        {
            get
            {
                return this.ProjectionField;
            }
            set
            {
                this.ProjectionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Activity", Namespace="http://schemas.datacontract.org/2004/07/PizzaCabinInc")]
    public partial class Activity : object
    {
        
        private string ColorField;
        
        private string DescriptionField;
        
        private System.DateTime StartField;
        
        private int minutesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color
        {
            get
            {
                return this.ColorField;
            }
            set
            {
                this.ColorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Start
        {
            get
            {
                return this.StartField;
            }
            set
            {
                this.StartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int minutes
        {
            get
            {
                return this.minutesField;
            }
            set
            {
                this.minutesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PizzaCabinInc.IPizzaCabinInc")]
    public interface IPizzaCabinInc
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaCabinInc/Schedule", ReplyAction="http://tempuri.org/IPizzaCabinInc/ScheduleResponse")]
        System.Threading.Tasks.Task<PizzaCabinInc.TeamSchedule> ScheduleAsync(string date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IPizzaCabinIncChannel : PizzaCabinInc.IPizzaCabinInc, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class PizzaCabinIncClient : System.ServiceModel.ClientBase<PizzaCabinInc.IPizzaCabinInc>, PizzaCabinInc.IPizzaCabinInc
    {
        
        public PizzaCabinIncClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<PizzaCabinInc.TeamSchedule> ScheduleAsync(string date)
        {
            return base.Channel.ScheduleAsync(date);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
